#!/bin/bash

script_dir=$(cd $(dirname $0) && pwd)
root_dir=$(cd $script_dir/.. && pwd)

source_dir=${1:-"$root_dir/llvm"}
build_dir=${2:-"$script_dir/build"}
install_dir=${3:-"$script_dir/install"}
build_type=${4:-"Release"}
assertions=${5:-"OFF"}
target_triple=${6:-"host"}
libcxx=${7:-"ON"}
warning=${8:-"ON"}
generator=${9:-"Ninja"}
compiler_launcher=${10:-""}
cc_compiler=${11:-""}
cxx_compiler=${12:-""}
max_args_count=12

shift_count=$(( $# < $max_args_count ? $# : $max_args_count ))
shift $shift_count

mkdir -p $build_dir
mkdir -p $install_dir

cmake_args=()

if [ -n "$compiler_launcher" ]; then
    cmake_args+=("-DCMAKE_C_COMPILER_LAUNCHER=$compiler_launcher")
    cmake_args+=("-DCMAKE_CXX_COMPILER_LAUNCHER=$compiler_launcher")
fi

if [ -n "$cc_compiler" ]; then
    cmake_args+=("-DCMAKE_C_COMPILER=$cc_compiler")
fi

if [ -n "$cxx_compiler" ]; then
    cmake_args+=("-DCMAKE_CXX_COMPILER=$cxx_compiler")
fi

if [ "$#" -gt 0 ]; then
    cmake_args+=("$@")
fi

echo "extra cmake args: ${cmake_args[@]}"

# Run `cmake -N -L -S llvm -B ./.alcy/build` or open `llvm/docs/CMake.rst` to see all build flags
cmake -S "$source_dir" -B "$build_dir" -G "$generator" \
  -DCMAKE_INSTALL_PREFIX="$install_dir" \
  -DCMAKE_BUILD_TYPE="$build_type" \
  -DLLVM_ENABLE_ASSERTIONS=$assertions \
  -DLLVM_DEFAULT_TARGET_TRIPLE=$target_triple \
  -DLLVM_ENABLE_LIBCXX=$libcxx \
  -DLLVM_ENABLE_WARNINGS=$warning \
  -DLLVM_TARGETS_TO_BUILD=all \
  -DBUILD_SHARED_LIBS=OFF \
  -DLLVM_ABI_BREAKING_CHECKS=WITH_ASSERTS \
  -DLLVM_BUILD_32_BITS=OFF \
  -DLLVM_BUILD_BENCHMARKS=OFF \
  -DLLVM_BUILD_DOCS=OFF \
  -DLLVM_BUILD_EXAMPLES=OFF \
  -DLLVM_BUILD_EXTERNAL_COMPILER_RT=OFF \
  -DLLVM_BUILD_LLVM_C_DYLIB=OFF \
  -DLLVM_BUILD_LLVM_DYLIB=OFF \
  -DLLVM_BUILD_RUNTIME=OFF \
  -DLLVM_BUILD_RUNTIMES=OFF \
  -DLLVM_BUILD_TESTS=OFF \
  -DLLVM_BUILD_TOOLS=OFF \
  -DLLVM_BUILD_UTILS=OFF \
  -DLLVM_DYLIB_COMPONENTS="" \
  -DLLVM_ENABLE_BACKTRACES=ON \
  -DLLVM_ENABLE_BINDINGS=OFF \
  -DLLVM_ENABLE_CRASH_DUMPS=OFF \
  -DLLVM_ENABLE_CRASH_OVERRIDES=ON \
  -DLLVM_ENABLE_CURL=OFF \
  -DLLVM_ENABLE_DAGISEL_COV=OFF \
  -DLLVM_ENABLE_DEBUGLOC_COVERAGE_TRACKING=DISABLED \
  -DLLVM_ENABLE_DOXYGEN=OFF \
  -DLLVM_ENABLE_DUMP=OFF \
  -DLLVM_ENABLE_EH=OFF \
  -DLLVM_ENABLE_EXPENSIVE_CHECKS=OFF \
  -DLLVM_ENABLE_EXPORTED_SYMBOLS_IN_EXECUTABLES=ON \
  -DLLVM_ENABLE_FATLTO=OFF \
  -DLLVM_ENABLE_FFI=OFF \
  -DLLVM_ENABLE_GISEL_COV=OFF \
  -DLLVM_ENABLE_HTTPLIB=OFF \
  -DLLVM_ENABLE_ICONV=OFF \
  -DLLVM_ENABLE_ICU=OFF \
  -DLLVM_ENABLE_IDE=OFF \
  -DLLVM_ENABLE_IO_SANDBOX=OFF \
  -DLLVM_ENABLE_LIBEDIT=OFF \
  -DLLVM_ENABLE_LIBPFM=OFF \
  -DLLVM_ENABLE_LIBXML2=OFF \
  -DLLVM_ENABLE_LLD=OFF \
  -DLLVM_ENABLE_LLVM_LIBC=OFF \
  -DLLVM_ENABLE_LOCAL_SUBMODULE_VISIBILITY=ON \
  -DLLVM_ENABLE_LTO=OFF \
  -DLLVM_ENABLE_MODULES=OFF \
  -DLLVM_ENABLE_MODULE_DEBUGGING=OFF \
  -DLLVM_ENABLE_NEW_PASS_MANAGER=ON \
  -DLLVM_ENABLE_OCAMLDOC=OFF \
  -DLLVM_ENABLE_ONDISK_CAS=ON \
  -DLLVM_ENABLE_PEDANTIC=ON \
  -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
  -DLLVM_ENABLE_PIC=ON \
  -DLLVM_ENABLE_PLUGINS=OFF \
  -DLLVM_ENABLE_PROFCHECK=OFF \
  -DLLVM_ENABLE_PROJECTS="" \
  -DLLVM_ENABLE_RTTI=OFF \
  -DLLVM_ENABLE_RUNTIMES="" \
  -DLLVM_ENABLE_SPHINX=OFF \
  -DLLVM_ENABLE_TELEMETRY=ON \
  -DLLVM_ENABLE_THREADS=ON \
  -DLLVM_ENABLE_UNWIND_TABLES=ON \
  -DLLVM_ENABLE_WERROR=OFF \
  -DLLVM_ENABLE_Z3_SOLVER=OFF \
  -DLLVM_ENABLE_ZLIB=OFF \
  -DLLVM_ENABLE_ZSTD=OFF \
  -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=OFF \
  -DLLVM_FORCE_ENABLE_STATS=OFF \
  -DLLVM_FORCE_USE_OLD_TOOLCHAIN=OFF \
  -DLLVM_INCLUDE_BENCHMARKS=OFF \
  -DLLVM_INCLUDE_DOCS=OFF \
  -DLLVM_INCLUDE_EXAMPLES=OFF \
  -DLLVM_INCLUDE_RUNTIMES=OFF \
  -DLLVM_INCLUDE_TESTS=OFF \
  -DLLVM_INCLUDE_TOOLS=OFF \
  -DLLVM_INCLUDE_UTILS=OFF \
  -DLLVM_INDIVIDUAL_TEST_COVERAGE=OFF \
  -DLLVM_INSTALL_BINUTILS_SYMLINKS=OFF \
  -DLLVM_INSTALL_CCTOOLS_SYMLINKS=OFF \
  -DLLVM_INSTALL_GTEST=OFF \
  -DLLVM_INSTALL_MODULEMAPS=OFF \
  -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
  -DLLVM_INSTALL_UTILS=OFF \
  -DLLVM_STATIC_LINK_CXX_STDLIB=OFF \
  -DLLVM_TOOL_DRAGONEGG_BUILD=OFF \
  -DLLVM_TOOL_OPENMP_BUILD=OFF \
  -DLLVM_UNREACHABLE_OPTIMIZE=ON \
  -DLLVM_USE_FOLDERS=ON \
  -DLLVM_USE_INTEL_JITEVENTS=OFF \
  -DLLVM_USE_OPROFILE=OFF \
  -DLLVM_USE_PERF=OFF \
  -DLLVM_USE_RELATIVE_PATHS_IN_DEBUG_INFO=OFF \
  -DLLVM_USE_RELATIVE_PATHS_IN_FILES=OFF \
  -DLLVM_USE_SANITIZER= \
  -DLLVM_USE_SPLIT_DWARF=ON \
  -DLLVM_USE_STATIC_ZSTD=OFF \
  -DLLVM_USE_SYMLINKS=ON \
  -DLLVM_VERSION_PRINTER_SHOW_BUILD_CONFIG=ON \
  -DLLVM_VERSION_PRINTER_SHOW_HOST_TARGET_INFO=ON \
  -DLLVM_WINDOWS_PREFER_FORWARD_SLASH=OFF \
  "${cmake_args[@]}"
