name: Build and Release LLVM Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - 'alcy_*'

jobs:
  build:
    name: Build and Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: macos-latest
            triple: x86_64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc

    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v6

      - name: Free Disk Space (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Install Ninja
        uses: llvm/actions/install-ninja@main

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-llvm-ccache
          max-size: 2G

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S llvm -B build -G Ninja \
            -DCMAKE_INSTALL_PREFIX=./install \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DLLVM_TARGETS_TO_BUILD=all \
            -DBUILD_SHARED_LIBS=OFF \
            -DLLVM_BUILD_32_BITS=OFF \
            -DLLVM_BUILD_BENCHMARKS=OFF \
            -DLLVM_BUILD_DOCS=OFF \
            -DLLVM_BUILD_EXAMPLES=OFF \
            -DLLVM_BUILD_EXTERNAL_COMPILER_RT=OFF \
            -DLLVM_BUILD_LLVM_C_DYLIB=OFF \
            -DLLVM_BUILD_LLVM_DYLIB=OFF \
            -DLLVM_BUILD_RUNTIME=OFF \
            -DLLVM_BUILD_RUNTIMES=OFF \
            -DLLVM_BUILD_TESTS=OFF \
            -DLLVM_BUILD_TOOLS=OFF \
            -DLLVM_BUILD_UTILS=OFF \
            -DLLVM_ENABLE_ASSERTIONS=OFF \
            -DLLVM_ENABLE_BACKTRACES=ON \
            -DLLVM_ENABLE_BINDINGS=OFF \
            -DLLVM_ENABLE_CRASH_DUMPS=OFF \
            -DLLVM_ENABLE_CRASH_OVERRIDES=ON \
            -DLLVM_ENABLE_CURL=OFF \
            -DLLVM_ENABLE_DAGISEL_COV=OFF \
            -DLLVM_ENABLE_DEBUGLOC_COVERAGE_TRACKING=DISABLED \
            -DLLVM_ENABLE_DOXYGEN=OFF \
            -DLLVM_ENABLE_DUMP=OFF \
            -DLLVM_ENABLE_EH=OFF \
            -DLLVM_ENABLE_EXPENSIVE_CHECKS=OFF \
            -DLLVM_ENABLE_EXPORTED_SYMBOLS_IN_EXECUTABLES=ON \
            -DLLVM_ENABLE_FATLTO=OFF \
            -DLLVM_ENABLE_FFI=OFF \
            -DLLVM_ENABLE_GISEL_COV=OFF \
            -DLLVM_ENABLE_HTTPLIB=OFF \
            -DLLVM_ENABLE_ICONV=OFF \
            -DLLVM_ENABLE_ICU=OFF \
            -DLLVM_ENABLE_IDE=OFF \
            -DLLVM_ENABLE_IO_SANDBOX=OFF \
            -DLLVM_ENABLE_LIBCXX=ON \
            -DLLVM_ENABLE_LIBEDIT=OFF \
            -DLLVM_ENABLE_LIBPFM=OFF \
            -DLLVM_ENABLE_LIBXML2=OFF \
            -DLLVM_ENABLE_LLD=OFF \
            -DLLVM_ENABLE_LLVM_LIBC=OFF \
            -DLLVM_ENABLE_LOCAL_SUBMODULE_VISIBILITY=ON \
            -DLLVM_ENABLE_LTO=OFF \
            -DLLVM_ENABLE_MODULES=OFF \
            -DLLVM_ENABLE_MODULE_DEBUGGING=OFF \
            -DLLVM_ENABLE_NEW_PASS_MANAGER=TRUE \
            -DLLVM_ENABLE_OCAMLDOC=OFF \
            -DLLVM_ENABLE_ONDISK_CAS=ON \
            -DLLVM_ENABLE_PEDANTIC=ON \
            -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
            -DLLVM_ENABLE_PIC=ON \
            -DLLVM_ENABLE_PLUGINS=ON \
            -DLLVM_ENABLE_PROFCHECK=OFF \
            -DLLVM_ENABLE_RTTI=OFF \
            -DLLVM_ENABLE_SPHINX=OFF \
            -DLLVM_ENABLE_TELEMETRY=ON \
            -DLLVM_ENABLE_THREADS=ON \
            -DLLVM_ENABLE_UNWIND_TABLES=ON \
            -DLLVM_ENABLE_WARNINGS=ON \
            -DLLVM_ENABLE_WERROR=OFF \
            -DLLVM_ENABLE_Z3_SOLVER=OFF \
            -DLLVM_ENABLE_ZLIB=OFF \
            -DLLVM_ENABLE_ZSTD=OFF \
            -DLLVM_FORCE_ENABLE_STATS=OFF \
            -DLLVM_FORCE_USE_OLD_TOOLCHAIN=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_INCLUDE_DOCS=OFF \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_RUNTIMES=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_TOOLS=OFF \
            -DLLVM_INCLUDE_UTILS=OFF \
            -DLLVM_INDIVIDUAL_TEST_COVERAGE=OFF \
            -DLLVM_INSTALL_BINUTILS_SYMLINKS=OFF \
            -DLLVM_INSTALL_CCTOOLS_SYMLINKS=OFF \
            -DLLVM_INSTALL_GTEST=OFF \
            -DLLVM_INSTALL_MODULEMAPS=OFF \
            -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
            -DLLVM_INSTALL_UTILS=OFF \
            -DLLVM_TOOL_DRAGONEGG_BUILD=OFF \
            -DLLVM_TOOL_OPENMP_BUILD=OFF \
            -DLLVM_UNREACHABLE_OPTIMIZE=ON \
            -DLLVM_USE_FOLDERS=ON \
            -DLLVM_USE_INTEL_JITEVENTS=OFF \
            -DLLVM_USE_OPROFILE=OFF \
            -DLLVM_USE_PERF=OFF \
            -DLLVM_USE_RELATIVE_PATHS_IN_DEBUG_INFO=OFF \
            -DLLVM_USE_RELATIVE_PATHS_IN_FILES=OFF \
            -DLLVM_USE_SANITIZER= \
            -DLLVM_USE_SPLIT_DWARF=OFF \
            -DLLVM_USE_STATIC_ZSTD=FALSE \
            -DLLVM_USE_SYMLINKS=ON \
            -DLLVM_VERSION_PRINTER_SHOW_BUILD_CONFIG=ON \
            -DLLVM_VERSION_PRINTER_SHOW_HOST_TARGET_INFO=ON \
            -DLLVM_WINDOWS_PREFER_FORWARD_SLASH=OFF

      - name: Build and Install
        run: |
          ccache -z
          cmake --build build --target install
          ccache -s

      - name: Archive Binaries
        shell: bash
        run: |
          basename="llvm-${{ matrix.triple }}"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a $basename.zip ./install/*
          else
            tar -czf $basename.tar.gz -C ./install .
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: "llvm-${{ matrix.triple }}.*"
          draft: true
          append_body: true
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
