name: Build and Release LLVM Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - 'alcy_*'
env:
  build_dir: "./.alcy/build"
  install_dir: "./.alcy/install"

jobs:
  build:
    name: Build and Release (${{ matrix.triple }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
            cc: clang
            cxx: clang++
          - os: ubuntu-latest
            triple: x86_64-musl-linux-gnu
            cc: clang
            cxx: clang++
          - os: macos-latest
            triple: x86_64-apple-darwin
            cc: clang
            cxx: clang++
          - os: macos-latest
            triple: aarch64-apple-darwin
            cc: clang
            cxx: clang++
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
            cc: cl
            cxx: cl
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v6

      - name: Free Disk Space (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Install Ninja
        uses: llvm/actions/install-ninja@main

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-llvm-ccache
          max-size: 4G

      - name: Setup mold
        if: runner.os == 'Linux'
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444
        with:
          mold-version: 2.41.0
          make-default: true

      - name: Install musl-tools
        if: matrix.triple == 'x86_64-musl-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756

      - name: Configure CMake
        run: |
          export CC="${{ matrix.cc }}"
          export CXX="${{ matrix.cxx }}"
          
          ./.alcy/configure.sh ./llvm $build_dir $install_dir Release Ninja ccache "" "" -DLLVM_DEFAULT_TARGET_TRIPLE="${{ matrix.triple }}"

      - name: Build and Install
        run: |
          ccache -z
          cmake --build $build_dir --target install -j
          ccache -s

      - name: Archive Binaries
        run: |
          basename="llvm-${{ matrix.triple }}"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a $basename.zip $install_dir/*
          else
            tar -czf $basename.tar.gz -C $install_dir .
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            llvm-${{ matrix.triple }}.zip
            llvm-${{ matrix.triple }}.tar.gz
          draft: true
          append_body: true
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
