name: Build and Release LLVM Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - 'alcy_*'
env:
  build_dir: "./.alcy/build"
  install_dir: "./.alcy/install"

jobs:
  build:
    name: Build and Release (${{ matrix.triple }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
            cc: clang
            cxx: clang++
            libcxx: true
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-musl
            cc: clang
            cxx: clang++
            libcxx: true
          - os: ubuntu-latest
            triple: riscv64-unknown-linux-gnu
            cc: clang
            cxx: clang++
            libcxx: true
          - os: macos-latest
            triple: x86_64-apple-darwin
            cc: clang
            cxx: clang++
            libcxx: true
          - os: macos-latest
            triple: aarch64-apple-darwin
            cc: clang
            cxx: clang++
            libcxx: true
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
            cc: clang
            cxx: clang++
            libcxx: false
    # env:
    #   CC: ${{ matrix.cc }}
    #   CXX: ${{ matrix.cxx }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout LLVM
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libc++-dev libc++abi-dev clang

      - name: Install Ninja
        uses: llvm/actions/install-ninja@89a8cf80982d830faab019237860b344a6390c30

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@4d0316e3a1f3f3c1a7a424368dc64f860c345402
        with:
          key: ${{ matrix.os }}-${{ matrix.triple }}-${{ matrix.cc }}-llvm-ccache
          max-size: 4G
          job-summary: ""

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3
        with:
          cmake-version: 4.3.2

      - name: Setup mold
        if: runner.os == 'Linux'
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444
        with:
          mold-version: 2.41.0
          make-default: true

      - name: Install musl-tools
        if: matrix.triple == 'x86_64-musl-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Configure CMake
        run: |
          ./.alcy/configure.sh ./llvm $build_dir $install_dir Release Ninja ccache ${{ matrix.cc }} ${{ matrix.cxx }} -DLLVM_DEFAULT_TARGET_TRIPLE="${{ matrix.triple }}" -DLLVM_ENABLE_LIBCXX="${{ matrix.libcxx }}"

      - name: Build and Install
        run: |
          ccache -z
          cmake --build $build_dir --target install -j
          ccache -s

      - name: Archive Binaries
        run: |
          basename="llvm-${{ matrix.triple }}"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a $basename.zip $install_dir/*
          else
            tar -czf $basename.tar.gz -C $install_dir .
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            llvm-${{ matrix.triple }}.zip
            llvm-${{ matrix.triple }}.tar.gz
          draft: true
          append_body: true
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
